[server]
address = "localhost"
showEmailPrompt = false
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = false

[theme]
primaryColor = "#28a745"
backgroundColor = "#f6fbfe"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"